# Generated by Django 2.2.1 on 2019-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('creation_date', models.CharField(max_length=20)),
                ('isRead', models.BooleanField(default=True)),
            ],
        ),
    ]
